<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [
        'bot_name' => env('TELEGRAM_BOT_NAME'),
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => true,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),

    'group_token' => env('TELEGRAM_GROUP_TOKEN'),
    'group_bot_name' => env('TELEGRAM_GROUP_BOT_NAME'),
    'developers' => env('TELEGRAM_LOG_CHAT_ID'),
    'superusers' => env('TELEGRAM_SUPERUSERS'),
];
